In [57]:
import pandas as pd
import geonamescache as gc


df = pd.read_csv('news_headline_info.csv')
gnc = gc.GeonamesCache()

latitude = []
longitude = []
country_code = []
for index in df.index:
    city = df['cities'][index]
    val = gnc.get_cities_by_name(city)
    
    if (city == "NaN" or val == []):
        latitude.append('NaN')
        longitude.append('NaN')
        country_code.append('NaN')
    elif (len(val) == 1):
        keys = [e for e in val[0]]
        latitude.append(val[0][keys[0]]['latitude'])
        longitude.append(val[0][keys[0]]['longitude'])
        country_code.append(val[0][keys[0]]['countrycode'])
    else:
        maxpop = 0
        index = 0
        for j in range(len(val)):
            keys = [e for e in val[j]]
            population = val[j][keys[0]]['population']
            if (population > maxpop):
                maxpop = population
                index = j
        keys = [e for e in val[index]]
        latitude.append(val[index][keys[0]]['latitude'])
        longitude.append(val[index][keys[0]]['longitude'])
        country_code.append(val[index][keys[0]]['countrycode'])

df['latitude'] = latitude
df['longitude'] = longitude
df['countrycode'] = country_code
del df['countries']

df.to_csv('latitude_longitude.csv')
df

,headline,cities,latitude,longitude,countrycode
0,Zika Outbreak Hits Miami,Miami,25.7743,-80.1937,US
1,Could Zika Reach New York City?,New York City,40.7143,-74.006,US
2,First Case of Zika in Miami Beach,Miami Beach,25.7906,-80.13,US
3,"Mystery Virus Spreads in Recife, Brazil",Recife,-8.05389,-34.8811,BR
4,Dallas man comes down with case of Zika,Dallas,32.7831,-96.8067,US
...,...,...,...,...,...
645,Rumors about Rabies spreading in Jerusalem hav...,Jerusalem,31.769,35.2163,IL
646,More Zika patients reported in Indang,Indang,14.1953,120.877,PH
647,Suva authorities confirmed the spread of Rotav...,Suva,-18.1416,178.441,FJ
648,More Zika patients reported in Bella Vista,Bella Vista,18.4554,-69.9454,DO
649,Zika Outbreak in Wichita Falls,Wichita Falls,33.9137,-98.4934,US